#!/usr/bin/env bash

scriptdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
rootdir="${scriptdir}/.."

rm -rf ${rootdir}/vendor
rm -rf ${rootdir}/web/core
rm -rf ${rootdir}/web/modules/contrib
rm -rf ${rootdir}/web/profiles/contrib
rm -rf ${rootdir}/web/themes/contrib

bash "${scriptdir}/uninstalldrupal"
